
all_readings <- weathercan::weather_dl(station_ids = c(6576,
                                                       6583,
                                                       6584,
                                                       6590,
                                                       6613,
                                                       6615,
                                                       6633,
                                                       6668,
                                                       6693,
                                                       6720,
                                                       6740,
                                                       6773,
                                                       6774,
                                                       6777,
                                                       6781,
                                                       6783,
                                                       6787,
                                                       6802,
                                                       10227,
                                                       10887,
                                                       45047,
                                                       45287,
                                                       49629,
                                                       50068,
                                                       50088,
                                                       50089,
                                                       51057,
                                                       51918,
                                                       51999,
                                                       ),
                                       interval = "hour",
                                       start = "1984-01-01",
                                       end = "2013-12-31",
                                       trim = TRUE,
                                       format = TRUE,
                                       stn = weathercan::stations,
                                       url = NULL,
                                       encoding = "UTF-8")

write.csv(all_readings,
          "C:\\Data\\GS2310\\CAPSTONE\\GS3210_StGeorge\\Arena\\RAW_DATA\\EC_DATA\\all_readings.csv",
          row.names = TRUE)


